# Generated by Django 4.1.2 on 2022-10-29 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CafeApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='pedidos',
            new_name='order',
        ),
    ]
