# Generated by Django 4.1.2 on 2022-11-21 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CafeApp', '0003_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(default=0, upload_to=''),
            preserve_default=False,
        ),
    ]
