# Generated by Django 4.1.2 on 2022-11-25 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CafeApp', '0007_remove_producto_icon_alter_producto_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='imagen',
        ),
    ]
