# Generated by Django 4.1.2 on 2022-11-25 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CafeApp', '0011_alter_producto_imagen_producto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='imagen_producto',
            new_name='imagen',
        ),
    ]
