# Generated by Django 4.1.2 on 2022-11-26 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CafeApp', '0012_rename_imagen_producto_producto_imagen'),
    ]

    operations = [
        migrations.DeleteModel(
            name='order',
        ),
    ]
