# Generated by Django 4.1.2 on 2022-11-26 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CafeApp', '0013_delete_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=50)),
                ('apellido_cliente', models.CharField(max_length=50)),
                ('email_cliente', models.EmailField(max_length=254)),
                ('items_cliente', models.CharField(max_length=100)),
                ('precio_total', models.IntegerField()),
            ],
        ),
    ]
