# Generated by Django 4.1.2 on 2022-11-26 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CafeApp', '0014_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='items_cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CafeApp.producto'),
        ),
    ]
