# Generated by Django 4.1.2 on 2022-11-26 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CafeApp', '0016_remove_order_precio_total_alter_order_items_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='precio_total',
            field=models.IntegerField(default=0),
        ),
    ]
