# Generated by Django 4.1.2 on 2022-11-26 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CafeApp', '0017_order_precio_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='precio_total',
            field=models.IntegerField(),
        ),
    ]
