# Generated by Django 4.1.2 on 2022-11-27 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CafeApp', '0018_alter_order_precio_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='comanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=50)),
                ('mesa', models.IntegerField()),
                ('items_cliente', models.CharField(max_length=100)),
                ('precio_total', models.IntegerField()),
            ],
        ),
    ]
